### ISSUE TITLE
运行出问题

### ISSUE THREAD

**Issue by wwwyz** [wongnoubo/ethereum_shop_dapp#1]
当我运行项目，买入游戏币点击兑换时，提示invalid address，我个人怀疑是index.js代码中的web3.eth.accounts[0]不能使用（在web3新版本中），但不知道怎么修改，在此请教一下博主，这个问题该怎么解决呢

**Comment by wwwyz** [comment]
最开始我是以为truffle版本、web3js版本的问题，于是去卸载当前版本换成推荐的版本，结果均无济于事，仍然出现这个错误（在win10、MAC系统下都存在），最终灵机一动，尝试着去换metamask版本，换成了6.2.2版本（之前是6.3.0），结果终于解决这个问题了，真的是意想不到，附上个人的运行环境及软件版本：操作系统：MAC OS，nodejs：10.15.3，truffle：5.0.13，npm：6.9.0，ganache：2.0.1，meatamask：6.2.2，ipfs：0.4.20。最后十分感谢git主的代码，愿git主工作顺利，万事如意！

**Comment by wongnoubo** [comment]
感谢兄弟！
